### ISSUE TITLE
Banned on discord 

### ISSUE THREAD

**Issue by IDAZIZ** [Hawkeye32/RJWHawk.BondOnly#1]
hey Hawk
sorry to bother you, 
i couldn't find you on loverslab, this is the only place where i can contact you that i could find.

 

i just got banned off discord after getting attacked by a bunch of people because they didn't like what i said 
and to be fair i haven't said anything wrong other than trolling them for their toxic behavior.

 

i've been in the discord for many years with the regular states, i hope you can help me with this

thank you.

**Comment by Hawkeye32** [comment]
If you haven't heard yet I believe the other mods were talking about it. I
think you're being let in but to keep a low profile for a bit.
